layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /blog/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - alsoknownasdrew.github.io
     - php-starter
     - alsoknownasdrew
     - eloquent-js
     - devto-blog-poc

social_media:
  instagram: alsoknownasdrew
  linkedin: frankevych
  twitter: alsoknownasdrew
