version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: .docker/dev/node/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8000:1234
    command: npm start
